# Generated by Django 3.0.5 on 2020-04-16 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
    ]
