# Generated by Django 3.0.5 on 2020-04-16 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitshare', '0002_workout_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=200, unique=True)),
                ('mechanic', models.CharField(max_length=200, unique=True)),
                ('force', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.TextField()),
                ('execution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='classification_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitshare.ExerciseClassification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='instruction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitshare.ExerciseInstruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitshare.ExerciseTarget'),
            preserve_default=False,
        ),
    ]
