# Generated by Django 3.0.5 on 2020-04-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitshare', '0003_auto_20200416_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='classification_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='instruction_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='type_id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='execution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='force',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='preparation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='utility',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ExerciseClassification',
        ),
        migrations.DeleteModel(
            name='ExerciseInstruction',
        ),
        migrations.DeleteModel(
            name='ExerciseTarget',
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
        migrations.DeleteModel(
            name='WorkoutType',
        ),
    ]
