# Generated by Django 3.0.5 on 2020-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitshare', '0004_auto_20200417_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user_alias',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
