# Generated by Django 3.0.5 on 2020-05-06 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitshare', '0007_auto_20200505_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='force',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='utility',
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_workout_name'),
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='exercise',
        ),
        migrations.AlterModelTable(
            name='workout',
            table='workout',
        ),
        migrations.AlterModelTable(
            name='workout_e',
            table='workout_e',
        ),
    ]
